name: reports_service
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: constructor_calculator
    ports:
      - "5000:5000" # закрыть внешний порт при включении в систему калькуляторов
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./input_files:/app/input_files # изменения в исходных файлах применяются после restart-а без пересборки
      - ./logs:/app/logs # логирование в реальном времени записывается в файл в проекте
      - ./output_files:/app/output_files # модуль может записывать выходные файлы в директорию проекта а не только контейнера
      - ./src:/app/src # изменения исходного кода применяются сразу после restart-а без сборки
      - ./.env:/app/.env # для быстрой замены значений в .env
    networks:
      - reports_service_network

networks:
  reports_service_network:
    driver: bridge
